server:
  port: 8081

spring:
#  application:
#    #应用的名称（可选）
#    name: bootblockchain
  datasource:
    druid:
      #driver-class-name: com.mysql.jdbc.Driver
      #url: jdbc:mysql://localhost:3306/bootblockchain?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blockchain?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      #password: ljc625995
      password: chenwenshuo123

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #使用雪花算法填充主键
      id-type: ASSIGN_ID

bootblockchain:
  path: D:\MyCode\JavaProject\reggie_take_out\uploadPicture\
